# Generated by Django 5.1.4 on 2024-12-24 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='liked',
            name='status',
            field=models.CharField(choices=[('liked', 'Liked'), ('unliked', 'Unliked')], default='liked', max_length=10),
        ),
        migrations.AlterField(
            model_name='liked',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.post'),
        ),
    ]
